---
- name: update motd file
  hosts: ungrouped
  user: vagrant
  become: true
  vars:
    motd_warning: "WARNING: used by ICT faculty/students only.\n\n"
  tasks:
    - name: setup a Message Of The Day
      copy:
        dest: /etc/motd
        content: "{{ motd_warning }}"
